---
prelude: >
    Enable an admin to configure a global serach domain.
    This is used if no search domain is confugured on a
    subnet.
features:
  - A new configuration variable in the nsxv section will
    enable the admin to configure a serach domain. The new
    variable is dns_search_domain.
