- project:
    templates:
      - openstack-python-jobs-neutron
      - check-requirements
      - openstack-python35-jobs-neutron
    check:
      jobs:
        - vmware-tox-lower-constraints
        - build-openstack-sphinx-docs
        - openstack-tox-pep8
        - openstack-tox-py27:
            timeout: 5400
        - openstack-tox-py35:
            timeout: 5400
    gate:
      queue: vmware-nsx
      jobs:
        - vmware-tox-lower-constraints
        - build-openstack-sphinx-docs
        - openstack-tox-pep8
        - openstack-tox-py27:
            timeout: 5400
        - openstack-tox-py35:
            timeout: 5400
    post:
      jobs:
        - publish-openstack-python-branch-tarball

- job:
    name: vmware-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    timeout: 5400
