- project:
    templates:
      - openstack-python-jobs-neutron
      - check-requirements
      - openstack-python35-jobs-neutron
      - periodic-stable-jobs-neutron
      - periodic-jobs-with-neutron-lib-master
      - publish-to-pypi-neutron
    check:
      jobs:
        - vmware-tox-lower-constraints
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py35:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
    gate:
      queue: vmware-nsx
      jobs:
        - vmware-tox-lower-constraints
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py35:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
    release:
      jobs:
        - release-openstack-python:
            required-projects:
              - openstack/neutron
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - openstack/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
- job:
    name: vmware-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    timeout: 5400
    required-projects:
      - openstack/neutron
      - openstack/networking-l2gw
      - openstack/networking-sfc
      - openstack/neutron-lbaas
      - openstack/vmware-nsxlib
      - openstack/neutron-fwaas
      - openstack/neutron-dynamic-routing
      - openstack/neutron-vpnaas
      - openstack/tap-as-a-service
