- job:
    name: vmware-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    timeout: 5400

- project:
    check:
      jobs:
        - vmware-tox-lower-constraints
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - vmware-tox-lower-constraints
            required-projects:
              - openstack/neutron
