- project:
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
- job:
    name: openstack-tox-lower-constraints
    timeout: 5400
